### ISSUE TITLE
for help ! in time

### ISSUE THREAD

**Issue by supergyz** [gundamMC/DL-Chatbot#1]
hello bro, i saw your question "why seq2seq chatbot give same answer" in stackoverflow
and i meet the same question as you , do you have solve it ,please give me some advice,thank you!

**Comment by gundamMC** [comment]
Sadly, no.
I did notice the repeating EOS/GO tokens getting replaced with actual words when I decreased the batch size and trained a lot more. Nevertheless, the network still fails to generate meaningful output. Due to various reasons, I do not have time to look deeper into this issue, but I'll try to do something with it when I can.

**Comment by supergyz** [comment]
thanks for your reply! I have sloved it ,bro. the way is to train it more... i run it on another computer with two 1080ti-GPU, and after thousands of step, it can generate different answers although they are not so meaningful. Hope it can help you ~~

**Comment by gundamMC** [comment]
Sounds great.
I was actually training with a GTX1060 6G, so it could be very possible that I did not train it enough lol.
Anyways, thanks for responding!

**Comment by gundamMC** [comment]
Sorry for the extremely late response.
This issue is resolved in 41bb0d95020ffdc374224dbaaf90f6a061265e53.

The problem was that the inputs and outputs of TrainingHelper/BasicDecoder are different. The ground truths (which you feed into TrainingHelper) contain the start token, while the outputs of the TrainingHelper (which you use for calculating cost) do not contain the start token. In other words,

Decoder input: <GO> foo bar <EOS>
Decoder output: foo bar <EOS>

This can be solved by removing the start tokens of y when computing the cost.
